### ISSUE TITLE
support for Oracle dialect?

### ISSUE THREAD

**Issue by streamnsight** [ariga/atlas#2912] opened 2024-07-02 01:36 UTC
SQLAlchemy supports Oracle dialect. Does Atlas supports it too? I don't see it in the list in the examples.

**Comment by rotemtam** [comment] 2024-07-02 05:34
Hey @streamnsight 

Thanks for reaching out. Oracle support is in the works and still in its early stages. 

If this is blocking your company in a substantial way, feel free to ping me on Discord and we can see if we can work something out.

**Comment by ALubrano77** [comment] 2024-08-22 07:40
hi, 
is there a beta version to try and give feedback?
ty

**Comment by a8m** [comment] 2024-09-21 05:26
> is there a beta version to try and give feedback?

Not yet. 

Closing as this duplicate of https://github.com/ariga/atlas/issues/2297.

**Closed by a8m** 2024-09-21 05:26 UTC
