### ISSUE TITLE
Clickhouse driver

### ISSUE THREAD

**Issue by RealHarshThakur** [ariga/atlas#1572] opened 2023-04-01 15:34 UTC
It would be nice for Atlas to support Clickhouse.   

I have tried using Clickhouse MySQL's wire to use atlas against it but that didn't work:

```
atlas schema inspect \
  --url ...
mysql: querying schemas: Error 47 (00000): Code: 47. DB::Exception: Missing columns: 'DEFAULT_COLLATION_NAME' while processing query: 'SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM (SELECT name AS catalog_name, name AS schema_name, 'default' AS schema_owner, NULL AS default_character_set_catalog, NULL AS default_character_set_schema, NULL AS default_character_set_name, NULL AS sql_path FROM system.databases HAVING SCHEMA_NAME NOT IN ('information_schema', 'innodb', 'mysql', 'performance_schema', 'sys')) AS SCHEMATA WHER%  
``

**Comment by HeCorr** [comment] 2023-06-24 06:40
Duplicate of #1456

**Comment by giautm** [comment] 2023-11-07 15:03
Hello @RealHarshThakur, I checked with ClickHouseDB, and it doesn't accept MySQL's DDL to create/alter table. So, it's impossible to manages ClickHouses' resources via MySQL's wire.

I'm closing this issue due to duplicate with #1456. We will update new information on that issue.

Thank you,

**Closed by giautm** 2023-11-07 15:04 UTC
