### ISSUE TITLE
failed reading spec as *postgres.doc

### ISSUE THREAD

**Issue by robarchibald** [ariga/atlas#2566] opened 2024-02-21 19:54 UTC
Got a terrible error message today. Couldn't figure out what was wrong for the life of me, so I had to comment out each new column I had recently added until I found the issue.

Full error was this:

`Error: schemahcl: failed reading spec as *postgres.doc: set field "type": converting cty.Value to *schemahcl.Type: incorrect type type`

Error causing the issue was this:

```hcl
  column "obstetric_anesthesia_additional_units" {
    null    = true
    type    = number
    comment = "Used to report additional complexity beyond the normal services (From QTY FL)"
  }
```

Fix was to change `type=number` to `type=numeric`. Error neither told me the line of the error nor which type was incorrect.

**Comment by a8m** [comment] 2024-02-21 19:57
Thanks for reporting this, @robarchibald. The type-checker should catch this - I'll make sure it's handled.

**Comment by a8m** [comment] 2024-02-22 21:56
Hey, @robarchibald. I just tried that locally and I'm not able to reproduce this:

<img width="991" alt="image" src="https://github.com/ariga/atlas/assets/7413593/49520467-8409-4f43-a642-ed4c8f92effc">

What version do you use? Please, use the `atlas version` command to get this info.

**Comment by a8m** [comment] 2024-02-25 08:53
Closing, but note that some of the language tooling for Atlas, such as the type checker, is not part of this repository. If you build Atlas from source or use the community version, the type-checking is skipped.

**Closed by a8m** 2024-02-25 08:53 UTC
