### ISSUE TITLE
`CREATE VIEW` is ignored in schema

### ISSUE THREAD

**Issue by oxilor** [ariga/atlas#1546] opened 2023-03-20 15:39 UTC
Views are not created during `schema apply`. Example of the schema:
```sql
CREATE TABLE companies (
  id serial PRIMARY KEY,
  deleted_at timestamptz,
  name varchar(100) NOT NULL,
);

CREATE VIEW active_companies AS SELECT * FROM companies WHERE deleted_at IS NULL;
CREATE VIEW deleted_companies AS SELECT * FROM companies WHERE deleted_at IS NOT NULL;
```

**Comment by a8m** [comment] 2023-03-21 07:03
Hey @oxilor 👋 
`VIEW`s are currently not supported by Atlas, but we plan to add support for this soon. 

Closing as this duplicate of https://github.com/ariga/atlas/issues/1373.

**Closed by a8m** 2023-03-21 07:03 UTC

**Comment by oxilor** [comment] 2023-03-21 07:10
@a8m Are there approximate deadlines? I want to understand whether it is worth waiting or looking for another solution. I hope that this opportunity will appear soon, because I'm starting to love atlas :)

**Comment by a8m** [comment] 2023-03-21 07:40
> I hope that this opportunity will appear soon, because I'm starting to love atlas :)

Thanks for the kind words. 

You can still use Atlas, but just not manage VIEWs with it. See my comment about the time estimation - https://github.com/ariga/atlas/issues/1545#issuecomment-1477390974.
