### ISSUE TITLE
Cannot inspect views on v0.18.0

### ISSUE THREAD

**Issue by sfperusacdev** [ariga/atlas#2440] opened 2024-01-12 16:20 UTC
After updating to version v0.18.0, the tool no longer recognizes views in the database. In the previous version, v0.17.0, this functionality was present and working correctly.

I used this command:  `atlas schema inspect -u $(PG_STRING) > migrations/schema.hcl`

Thank you for your hard work on this tool.

**Comment by rotemtam** [comment] 2024-01-12 17:17
Hi there
Thanks for the kind words . Please use "atlas login" to activate views.
Best

**Comment by a8m** [comment] 2024-01-12 17:23
The reason views were moved to the login is that some rely on logged-in objects, such as functions or materialized views. We decided to move views to "login" as well to avoid the unexpected behavior that some users reported in the issue tracker.

Closing, but feel free to reopen or join our Discord if you still need help with this.

**Closed by a8m** 2024-01-12 17:23 UTC
