### ISSUE TITLE
Error: sql/schema: create "atlas_schema_revisions" table: pq: relation "atlas_schema_revisions" already exists

### ISSUE THREAD

**Issue by hsblhsn** [ariga/atlas#1123] opened 2022-09-04 11:33 UTC
Can not apply migration anymore.

When running this command
```
atlas migrate --dir file://ent/migrations apply --url=${DATABASE_URL}
```

I am getting `Error: sql/schema: create "atlas_schema_revisions" table: pq: relation "atlas_schema_revisions" already exists` this error.

**Comment by a8m** [comment] 2022-09-04 12:13
Hey @hsblhsn and sorry for the inconvenience. 
Do you run the migration on a specific schema or the entire database (if the `search_path` is empty or not)? Also, do you run multiple applications on the same database? Because I think https://github.com/ariga/atlas/pull/1120 should solve this issue if that's the case, or passing the schema-name as the `--revision-schema`.

**Comment by hsblhsn** [comment] 2022-09-04 13:14
This is the atlas version currently in use.

```
❯ atlas version
atlas version v0.6.5-a43e686-canary
https://github.com/ariga/atlas/releases/latest
```

No, I do not have multiple application running on the same database. And I am running the migration for the entire database. This is the migration files generated by ent.

```
❯ tree ./ent/migrations 
./ent/migrations
├── 20220902130324_make-ent.sql
├── 20220904090725_make-ent.sql
└── atlas.sum

0 directories, 3 files
```

And I am trying to apply it by calling `atlas migrate` and getting the error below:

```
❯ atlas migrate --dir file://ent/migrations apply --url=${DATABASE_URL}
Error: sql/schema: create "atlas_schema_revisions" table: pq: relation "atlas_schema_revisions" already exists
```

Thank you so much for the quick response.

**Comment by hsblhsn** [comment] 2022-09-04 13:18
FIXED!

After downgrading to `atlas` version `v0.6.0`, the problem got **fixed**. 😕 

So, I guess something is going wrong or breaking in the upcoming release.

My previous installation was with `brew install ariga/tap/atlas`. It installs the canary version. When I uninstalled it and downloaded `atlas v0.6.0` from the release page, the issue got fixed. No more error.

```
❯ atlas version
atlas version v0.6.0
https://github.com/ariga/atlas/releases/tag/v0.6.0

❯ atlas migrate --dir file://ent/migrations apply --url=${DATABASE_URL}
The migration directory is synced with the database, no migration files to execute
```

Strange 🕵️

**Comment by masseelch** [comment] 2022-09-04 13:56
Hey @hsblhsn, thank you for reporting this and sorry for the mess.

> FIXED!

I am happy you are unblocked :blush:, though we always aim for the best experience possible and rolling back is not that, I am sorry.

> Strange :detective:

The new release changes the default behavior for the schema history table, but it is not merged yet, though yeah, it is a little strange. I will investigate and notify you back, once I have eliminated the culprit for this.

**Comment by masseelch** [comment] 2022-09-05 07:35
Hey @hsblhsn, I was able to reproduce your issue: 

Create existing project with v.0.6.0:

```shell
# atlas-linux-amd64-v0.6.0 migrate apply -u "postgres://postgres:nopass@localhost:5432/postgres?sslmode=disable"
Migrating to version 20220905071944 (1 migrations in total):

  -- migrating version 20220905071944
    -> CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, PRIMARY KEY ("id"));
  -- ok (4.689575ms)

  -------------------------
  -- 7.114855ms
  -- 1 migrations
  -- 1 sql statements
```

Confirm latest release shows your issue:

```shell
# atlas-linux-amd64-latest migrate apply -u "postgres://postgres:nopass@localhost:5432/postgres?sslmode=disable"
Error: sql/schema: create "atlas_schema_revisions" table: pq: relation "atlas_schema_revisions" already exists
```

However, the PR I am about to merge, does fix the issue:

```shell
# atlas/build/atlas migrate apply -u "postgres://postgres:nopass@localhost:5432/postgres?sslmode=disable"
The migration directory is synced with the database, no migration files to execute
```

I will close this issue, if you continue to have problems, please re-open and I will do my best to help.

**Closed by masseelch** 2022-09-05 07:35 UTC

**Comment by masseelch** [comment] 2022-09-05 08:24
Some more context:

Previous to the changes made in [this PR](https://github.com/ariga/atlas/pull/1108/files#diff-64a455fde41235dd02bec791f701d15f090c2003cb39fe20373bd0152189d6bc) Atlas operated on two different connections for migration execution (actual migration and revision history). Since in that case we don't have the atomicity of the database connection any more (important for transactions), we changed that. 

Sadly this led to a bug in the migration engine: It computed the revision table diff between the connected schema (`public` in this case) and the schema of the revision table (`atlas_schema_revisions`). Since the table resides in the latter and did not exist in the former, the engine wanted to create the table and of course that raised the error.

![image](https://user-images.githubusercontent.com/12862103/188403512-f14f99e1-603b-40a3-a785-0996cd503ea2.png)

However, the latest master [fixed this bug](https://github.com/ariga/atlas/pull/1120/files#diff-64a455fde41235dd02bec791f701d15f090c2003cb39fe20373bd0152189d6bc) by using a second connection for the revision table migration, now bound to the correct schema. 

![image](https://user-images.githubusercontent.com/12862103/188403604-68435741-94b0-4092-b25f-2353132b8981.png)
