### ISSUE TITLE
Support of views and functions

### ISSUE THREAD

**Issue by althaf004** [ariga/atlas#1842] opened 2023-07-10 06:11 UTC
While generating schema migrations, we currently only obtain scripts related to tables. Views and functions are not included in the script. I would like to know if this will be a feature in upcoming versions or if there are any reasons behind this decision.

**Comment by rotemtam** [comment] 2023-07-10 06:48
Hi @althaf004,

Support for views is coming really soon 😍 

Duplicate of:
https://github.com/ariga/atlas/issues/1373

Closing

**Closed by rotemtam** 2023-07-10 06:48 UTC

**Comment by linzhiq** [comment] 2023-08-28 05:12
@rotemtam any updates on including functions as well?

**Comment by althaf004** [comment] 2023-08-31 06:39
if functions where included, entire migration would be completed. shall we expect this any time sooner?
