### ISSUE TITLE
versioned migration throwing syntax error when creating functons in mariadb

### ISSUE THREAD

**Issue by lallenfrancisl** [ariga/atlas#1094] opened 2022-08-24 04:58 UTC
```sql
DELIMITER $$

CREATE OR REPLACE FUNCTION gen_uuid() RETURNS VARCHAR(22) 
BEGIN
    RETURN concat(
        date_format(NOW(6), '%Y%m%d%i%s%f'),
        ROUND(1 + RAND() * (100 - 2))
    );
END;$$

DELIMITER ;
```

This code throw syntax error at line 4 when running migration from the sql file.

atlas version: v0.6.0-f064262-canary
mariadb version:

**Comment by a8m** [comment] 2022-08-24 06:23
Hey @lallenfrancisl and thanks for reporting this issue.

Currently, the way to achieve this is by setting an Atlas pragma on the top of the file to configure the delimiter used for scanning the statements in the file. For example, the following file will be scanned as one statement because the `atlas:delimiter` is configured but it's not used.

```sql
-- atlas:delimiter ATLAS_DELIMITER

DELIMITER $$

CREATE OR REPLACE FUNCTION gen_uuid() RETURNS VARCHAR(22) 
BEGIN
    RETURN concat(
        date_format(NOW(6), '%Y%m%d%i%s%f'),
        ROUND(1 + RAND() * (100 - 2))
    );
END;$$

DELIMITER ;
```

In the next example, we use the `atlas:delimiter` in the file and the result is 2 statements:

```sql
-- atlas:delimiter ATLAS_DELIMITER

DELIMITER $$

CREATE OR REPLACE FUNCTION gen_uuid() RETURNS VARCHAR(22) 
BEGIN
    RETURN concat(
        date_format(NOW(6), '%Y%m%d%i%s%f'),
        ROUND(1 + RAND() * (100 - 2))
    );
END;$$

DELIMITER ;


ATLAS_DELIMITER

CALL gen_uuid();
```
More examples exist in the repository https://github.com/ariga/atlas/tree/master/sql/migrate/testdata/lex.

This behavior is expected to be improved soon as Atlas now supports parsing SQL files of all the supported dialects and I plan to integrate it into the file scanning as well. Please, let me know if you need more help or if I can close this issue 🙏

**Comment by lallenfrancisl** [comment] 2022-08-27 17:43
Thanks @a8m for the reply. Yes I didn't realise that from their documentation that this thing is only for their command line. For other SQL noobs like me I am just putting another solution here too. The delimiter thing is not actually needed in sql and this is enough
```sql
CREATE OR REPLACE FUNCTION gen_uuid() RETURNS VARCHAR(22) 
    RETURN concat(
        date_format(NOW(6), '%Y%m%d%i%s%f'),
        ROUND(1 + RAND() * (100 - 2))
    );
```

**Comment by lallenfrancisl** [comment] 2022-08-29 01:06
@a8m the solution you proposed still does not work, it will start to throw error at the place where DELIM is used
```sql
-- atlas:delimiter DELIM
CREATE TABLE `Client_m` (
    `ClientID` varchar(22) NOT NULL,
    `DataBackupDays` int NOT NULL,
    `ApiAccessKey` varchar(22) NOT NULL,
    `ClientAccessType` enum('Basic', 'Web') NULL,
    `Status` enum('0', '1', '2') NOT NULL,
    PRIMARY KEY (`ClientID`)
) CHARSET utf8mb4 COLLATE utf8mb4_general_ci; DELIM
```

```
Error: Execution had errors:
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIM

-- set default id value for ClientID
-- CREATE OR REPLACE TRIGGER Clie...' at line 1

Error: sql/migrate: execute: executing statement "DELIM\n\n-- set default id value for ClientID\n-- CREATE OR REPLACE TRIGGER Client_mClientID BEFORE\n-- INSERT ON `Client_m` FOR EACH ROW\n-- IF new.ClientID IS NULL OR LENGTH(new.ClientID) < 1\n--     THEN SET new.ClientID = gen_uuid();\n--     ELSE SET new.ClientID = new.ClientID;\n-- END IF;\n\n-- DELIM\n\n-- create \"Client_User\" table\nCREATE TABLE `Client_User` (\n    `UserID` varchar(22) NOT NULL,\n    `ClientID` varchar(22) NOT NULL,\n    `Status` enum('0', '1', '2') NOT NULL,\n    PRIMARY KEY (`UserID`)\n) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;" from version "20220822222238": Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIM

-- set default id value for ClientID
-- CREATE OR REPLACE TRIGGER Clie...' at line 1
make: *** [migrate-up] Error 1
```

**Comment by lallenfrancisl** [comment] 2022-08-29 01:21
Seems there was some issue since the pragma wasn't at the top so moved it top but got empty query error now
```sql
-- atlas:delimiter DELIM

-- create "Client_m" table
CREATE TABLE `Client_m` (
    `ClientID` varchar(22) NOT NULL,
    PRIMARY KEY (`ClientID`)
) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
DELIM

-- set default id value for ClientID
DELIMITER $$

CREATE OR REPLACE TRIGGER Client_mClientID BEFORE
INSERT ON `Client_m` FOR EACH ROW
IF new.ClientID IS NULL OR LENGTH(new.ClientID) < 1
    THEN SET new.ClientID = gen_uuid();
    ELSE SET new.ClientID = new.ClientID;
END IF;$$

DELIMITER ;
DELIM
```

```
Error: sql/migrate: execute: executing statement "" from version "20220822222238": Error 1065: Query was empty
make: *** [migrate-up] Error 1
```

**Comment by a8m** [comment] 2022-08-29 05:50
Hey @lallenfrancisl, it looks like the Atlas delimiter conflicts with the MySQL DELIMITER keyword.

Please, update to the latest master and checkout the docs on how to use a different delimiter instead (e.g. \n\n\n): https://atlasgo.io/versioned/new#custom-statements-delimiter

I also added a few additional examples to our tests, you can see them here: https://github.com/ariga/atlas/tree/master/sql/migrate/testdata/lex

**Comment by a8m** [comment] 2022-08-29 05:56
Another point that I think can be added to the docs is that the DELIMITER keyword is not needed when interacting with the server directly (not the MySQL CLI). See https://dev.mysql.com/doc/refman/8.0/en/stored-programs-defining.html

**Comment by lallenfrancisl** [comment] 2022-08-29 07:35
> Another point that I think can be added to the docs is that the DELIMITER keyword is not needed when interacting with the server directly (not the MySQL CLI). See https://dev.mysql.com/doc/refman/8.0/en/stored-programs-defining.html

Yeah but I think the driver needs it, not working without it

**Comment by a8m** [comment] 2022-08-29 08:08
Hey @lallenfrancisl 👋 
Can you please provide an example to reproduce this? I just ran the following example on the **master version** and it worked:

Migration file:
```sql
-- atlas:delimiter \n\n\n

CREATE PROCEDURE dorepeat(p1 INT)
BEGIN
    SET @x = 0;
    REPEAT SET @x = @x + 1; UNTIL @x > p1 END REPEAT;
END;


CALL dorepeat(1000);
```

`atlas migrate apply` output:

```text
Migrating to version 20220829075648 (1 migrations in total):

  -- migrating version 20220829075648
    -> CREATE PROCEDURE dorepeat(p1 INT)
BEGIN
    SET @x = 0;
    REPEAT SET @x = @x + 1; UNTIL @x > p1 END REPEAT;
END;
    -> CALL dorepeat(1000);
  -- ok (19.935ms)

  -------------------------
  -- 26.544929ms
  -- 1 migrations
  -- 2 sql statements
```

MySQL status:
```text
mysql> select routine_definition from information_schema.routines where routine_name='dorepeat';
+---------------------------------------------------------------------------------+
| ROUTINE_DEFINITION                                                              |
+---------------------------------------------------------------------------------+
| BEGIN
    SET @x = 0;
    REPEAT SET @x = @x + 1; UNTIL @x > p1 END REPEAT;
END |
+---------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

As I mentioned above, I think the `DELIMITER` is not something the MySQL server understands and is used only by the CLI.

**Comment by lallenfrancisl** [comment] 2022-08-29 08:50
I will give you an example to reproduce this in the evening, sorry should have put it here in the beginning

**Comment by a8m** [comment] 2022-08-29 08:54
No worries, and sorry for the inconvenience 🙏🏻

**Comment by a8m** [comment] 2022-10-09 11:15
Closing, as this issue was resolved a long time ago. Note that we also added support for the `DELIMITER` keyword used by MySQL client, see https://atlasgo.io/versioned/new#using-the-delimiter-command-used-by-mysql-client. 

Feel free to reopen it if you still have troubles with it, and you're also welcome to join our [Discord community](https://discord.gg/zZ6sWVg6NT).

**Closed by a8m** 2022-10-09 11:15 UTC
