### ISSUE TITLE
GORM Integration omits additional fields in many-to-many join tables when generating a migration file

### ISSUE THREAD

**Issue by JMBT-TS** [ariga/atlas#2544] opened 2024-02-15 05:03 UTC
When using GORMs [custom join tables feature](https://gorm.io/docs/many_to_many.html#Customize-JoinTable) to add additional fields to a (many-to-many relationship) join table, Atlas seems to ignore all additionally defined fields when generating a migration script with `atlas migrate diff --env gorm`.

**Example**
```go
import (
    "gorm.io/gorm"
    "time"
)

type PersonModel struct {
    CreatedAt time.Time
    UpdatedAt time.Time
    ID        uint
    Name      string
    Addresses []AddressModel `gorm:"many2many:person_addresses;joinForeignKey:PersonID;joinReferences:AddressID"`
}

func (PersonModel) TableName() string {
    return "person"
}

type AddressModel struct {
    CreatedAt time.Time
    UpdatedAt time.Time
    ID        uint
    Name      string
    People    []PersonModel `gorm:"many2many:person_addresses;joinForeignKey:AddressID;joinReferences:PersonID"`
}

func (AddressModel) TableName() string {
    return "address"
}

// custom join table
type PersonAddressModel struct {
    CreatedAt time.Time
    UpdatedAt time.Time
    PersonID  uint `gorm:"primaryKey"`
    Person    PersonModel
    AddressID uint `gorm:"primaryKey"`
    Address   AddressModel
    Deceased  bool `gorm:"notNull;default:false"`
}

func (PersonAddressModel) TableName() string {
    return "person_address"
}

func setupTables(db *gorm.DB) error {
    if err := db.SetupJoinTable(&PersonModel{}, "Addresses", &PersonAddressModel{}); err != nil {
        return err
    }
    if err := db.SetupJoinTable(&AddressModel{}, "People", &PersonAddressModel{}); err != nil {
        return err
    }
    return nil

}
```

This example will produce three tables in the database: `person`, `address`, and `person_address`. The `person_address` join-table will have three additional fields: `created_at`, `updated_at`, and `deceased`. When using `gorm.AutoMigrate`, it will create those three tables as described. However, when using `atlas migrate diff --env gorm` to generate a migration file, the created script does not contain the `created_at`, `updated_at`, and `deceased` column defined in the `PersonAddressModel`.

I am using the `go program mode` from the [Atlas documentation](https://atlasgo.io/guides/orms/gorm) on *Automatic migration planning for GORM*.
The application is using the `mysql` driver.

**Comment by noamcattan** [comment] 2024-02-15 08:24
When I ran your example, I got 4 tables in total: `address`, `person`, `person_address` and `person_addresses`.
`person_addresses` in fact only had two columns - `address_id` and `person_id`, but `person_address` had the additional ones you mentioned. And I got the exact same result when I used Gorms Automigrate. So I think either the issue is with Gorm, or the problem is not well defined.

Link to the visualization of the schema made by Atlas: https://gh.atlasgo.cloud/explore/db09bc65

And this is how the tables look like in the database (after running with Gorm Automigrate):
![image](https://github.com/ariga/atlas/assets/62568565/158066e0-900a-46a4-9b5a-cb1ba3b8010e)

**Comment by JMBT-TS** [comment] 2024-02-15 08:31
I am sorry, I made a small typo when creating the example. This should be the correct one:

```go
import (
    "gorm.io/gorm"
    "time"
)

type PersonModel struct {
    CreatedAt time.Time
    UpdatedAt time.Time
    ID        uint
    Name      string
    Addresses []AddressModel `gorm:"many2many:people_addresses;joinForeignKey:PersonID;joinReferences:AddressID"`
}

func (PersonModel) TableName() string {
    return "person"
}

type AddressModel struct {
    CreatedAt time.Time
    UpdatedAt time.Time
    ID        uint
    Name      string
    People    []PersonModel `gorm:"many2many:people_addresses;joinForeignKey:AddressID;joinReferences:PersonID"`
}

func (AddressModel) TableName() string {
    return "address"
}

// custom join table
type PersonAddressModel struct {
    CreatedAt time.Time
    UpdatedAt time.Time
    PersonID  uint `gorm:"primaryKey"`
    Person    PersonModel
    AddressID uint `gorm:"primaryKey"`
    Address   AddressModel
    Deceased  bool `gorm:"notNull;default:false"`
}

func (PersonAddressModel) TableName() string {
    return "people_addresses"
}

func setupTables(db *gorm.DB) error {
    if err := db.SetupJoinTable(&PersonModel{}, "Addresses", &PersonAddressModel{}); err != nil {
        return err
    }
    if err := db.SetupJoinTable(&AddressModel{}, "People", &PersonAddressModel{}); err != nil {
        return err
    }
    return nil

}
```

**Comment by noamcattan** [comment] 2024-02-15 08:44
Thank you, I'm able to reproduce it now. Will check.

**Comment by noamcattan** [comment] 2024-02-15 12:28
The error is related to the order of models as they are passed to `Automigrate` internally. The provider ends up doing something like this:
```go
db.Automigrate(&PersonAddressModel{}, &PersonModel{}, &AddressModel{})
```
So the linking table is created before it's dependencies, which causes it to be partially created. Looks like something that Gorm should handle, but appearantly it doesn't.
We will work on a fix for this, but in the meantime you can use the [go program mode](https://atlasgo.io/guides/orms/gorm#go-program-mode) which lets you control the order of models. So in your eample the progeam will look somehing like this:
```go
package main

import (
    "io"
    "os"

    "ariga.io/atlas-provider-gorm/gormschema"
    _ "ariga.io/atlas-provider-gorm/recordriver"
    "github.com/<yourorg>/<yourrepo>/path/to/models"
)

func main() {
    stmts, err := gormschema.New("mysql").Load(
        &models.PersonModel{},
	&models.AddressModel{},
	&models.PersonAddressModel{},
    )
    if err != nil {
        fmt.Fprintf(os.Stderr, "failed to load gorm schema: %v\n", err)
        os.Exit(1)
    }
    io.WriteString(os.Stdout, stmts)
}
```

**Comment by JMBT-TS** [comment] 2024-02-15 13:05
I am actually having this issue when using the `go program mode`. My loader `main` looks exactly like the example you just provided me with.

**Comment by noamcattan** [comment] 2024-02-18 09:19
> I am actually having this issue when using the `go program mode`. My loader `main` looks exactly like the example you just provided me with.

Hey! I tried to play with it a bit but couldn't reproduce the issue this way. Can you maybe send a more detailed example, or even maybe a link to a repository that demonstrate how to make the error happen?

**Comment by JMBT-TS** [comment] 2024-02-19 11:28
Here is an similar example of my `migrations/loader/main.go`. Unfortunately, I cannot share the actual source code.

```go
package main

import (
	"github.com/example/pkg/storage"
	"io"
	"log"
	"os"
	"ariga.io/atlas-provider-gorm/gormschema"
)

func main() {
	stmts, err := gormschema.New("mysql").Load(
		&storage.PersonModel{},
		&storage.AddressModel{},
		&storage.PersonAddressModel{},
	)
	if err != nil {
		log.Fatalf("failed to load gorm schema: %v", err)
	}
	_, err = io.WriteString(os.Stdout, stmts)
	if err != nil {
		log.Fatalf("failed to generate database migration: %v\n", err)
	}
}
```

This is what I use to run atlas `go:generate atlas migrate diff --env gorm`

And this is the `atlas.hcl` file in the root directory.

```
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "./migrations/loader"
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "docker://mysql/8/dev"
  migration {
    dir = "file://migrations/revisions"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```

**Comment by noamcattan** [comment] 2024-02-22 07:54
In your example, change the order of models from:
```go
		&storage.PersonModel{},
		&storage.PersonAddressModel{},
		&storage.AddressModel{},
```
to:
```go
		&storage.PersonModel{},
		&storage.AddressModel{},
		&storage.PersonAddressModel{},
```

And it should work.

**Comment by JMBT-TS** [comment] 2024-02-23 05:15
Maybe this should be added as a warning to the documentation, since Gorm `Automigrate` behaves differently and doesn't care about the order of models.

**Closed** 2024-03-07 05:45 UTC
