### ISSUE TITLE
Allow arbitrary index types 

### ISSUE THREAD

**Issue by mingfang** [ariga/atlas#2770] opened 2024-05-10 18:54 UTC
I'm using ParadeDB's bm25(https://github.com/paradedb/paradedb)index for search, and am getting this error 
```
Error: invalid index storage parameter:  min_gram: 4
```

It looks like the error is coming from here

https://github.com/ariga/atlas/blob/5922441c051dd131b7e86227893813d44cbc6222/sql/postgres/inspect.go#L1401

What is the reason to limit the index types?
Can we at least have an option to bypass this check?

**Comment by a8m** [comment] 2024-05-10 19:05
Thanks for reporting this, @mingfang.

> What is the reason to limit the index types?
> Can we at least have an option to bypass this check?

There's no option to bypass this check atm. We currently parse the specific Postgres format we support, as it's used in other stages like diffing, planning and when written as an HCL. 

I'm not sure what are the gaps between ParadeDB and our current Postgres driver, but these cases we'll be handled when we add support to it - I don't have ETA for this. 

Closing, as this is duplicate of https://github.com/ariga/atlas/issues/1472. I'll update it when the issue is resolved.

**Closed by a8m** 2024-05-10 19:05 UTC
