### ISSUE TITLE
List binary download links

### ISSUE THREAD

**Issue by j0hnsmith** [ariga/atlas#2434] opened 2024-01-11 08:34 UTC
This first of these links is listed under manual installation on https://atlasgo.io/community-edition but I had to guess the url for the second link. Can you have a page of links to all versions (including past ones)? Or include binaries on in the github releases?

https://release.ariga.io/atlas/atlas-darwin-arm64-latest
https://release.ariga.io/atlas/atlas-darwin-arm64-v0.17.0

**Comment by a8m** [comment] 2024-01-11 08:39
Hey @j0hnsmith 👋 

Most users just use `curl -sSf https://atlasgo.sh`. However, we understand that some users need access to this information, and we have plans to make this publicly available. 

Closing as this is a duplicate of https://github.com/ariga/atlas/issues/2303.

**Closed by a8m** 2024-01-11 08:39 UTC

**Comment by j0hnsmith** [comment] 2024-01-11 09:09
Ahh, I did search but didn't find that issue, sorry for the dup. `curl`ing an unknown remote script is rarely a good idea.
