### ISSUE TITLE
Scrolling is broken in docs

### ISSUE THREAD

**Issue by shachibista** [ariga/atlas#555] opened 2022-02-09 07:42 UTC
Hi!

Noticed that the scrolling is broken in the docs pages https://atlasgo.io/cli/getting-started/setting-up . Under Ubuntu 20.04 google chrome version 98.0.4758.80, I cannot scroll to the next page.

**Comment by yonidavidson** [comment] 2022-02-09 09:03
Hi @shachibista , thanks for raising the issue.
Can you please just elaborate for me, is the problem that you can't reach the "Next" button?
![image](https://user-images.githubusercontent.com/5472778/153161521-f3927203-968c-4f75-a5d9-4e4f8c44ec45.png)

**Comment by shachibista** [comment] 2022-02-11 00:42
That is correct, when I try to scroll down I the scroll position is reset to the top. 

https://user-images.githubusercontent.com/3925529/153520815-75906d7e-5cf8-4560-b5e1-ee3e70b5b321.mp4

**Comment by a8m** [comment] 2022-08-24 07:27
Hey @shachibista 👋 

We upgraded the [Docusaurus](https://docusaurus.io/) version and I hope it will solve the issue. Closing this as we are not able to reproduce this, but feel free to reopen it if you still face any problems with it. Thanks 🙏

**Closed by a8m** 2022-08-24 07:27 UTC
