### ISSUE TITLE
Diff is not generated correctly for db with existing materialized view

### ISSUE THREAD

**Issue by romansme** [ariga/atlas#2137] opened 2023-09-29 13:05 UTC
Hey!

We have a small issue when working with the latest atlas (v0.14.2-75e99bd-canary)
We wrote a materialized view, generated the diff and applied a migration - till now everything is ok
Then, without any additional changes we generate a diff again and get an error

```
Error: cannot modify materialized view "DailyAggregatedSalesInfo" definition
Error: Command failed:
    atlas migrate diff \
    --dir "file://migrations" \
    --to "file://schema/master_schema.sql"\
    --config "file://atlas.hcl"\
    --dev-url "postgresql://postgres:postgres@localhost:5432/testing?sslmode=disable"
```

when downgrading to atlas version v0.14.1-aa87e1b-canary it works fine

**Comment by a8m** [comment] 2023-09-29 14:11
Hey @romansme 👋 

Could you please provide more context or information about which version of PostgreSQL you are using, along with a small example that reproduces this issue?

**Comment by romansme** [comment] 2023-09-30 08:16
Hey!
Postgres version is 15.3

So actually the example is not as trivial as i thought :)
this is the sql we are working with: 

```
CREATE TABLE "Orders"
(
    "id"                             TEXT PRIMARY KEY,
    "companyId"                      TEXT                     NOT NULL
);

CREATE TABLE "OrderItems"
(
    "id"                           TEXT PRIMARY KEY,
    "orderId"                      TEXT REFERENCES "Orders" (id) NOT NULL
);

CREATE MATERIALIZED VIEW "DailyAggregatedSalesInfo" AS
select "Orders"."id"
from "OrderItems",
     "Orders"
where "OrderItems"."orderId" = "Orders".id
  and not exists(select 'x'
                 from "Orders"
                 where "Orders"."id" = "OrderItems"."orderId"
                   )
```

Note that when the materialized view condition doesn't include the "not exists" part - it works fine:



```
CREATE TABLE "Orders"
(
    "id"                             TEXT PRIMARY KEY,
    "companyId"                      TEXT                     NOT NULL
);

CREATE TABLE "OrderItems"
(
    "id"                           TEXT PRIMARY KEY,
    "orderId"                      TEXT REFERENCES "Orders" (id) NOT NULL
);

CREATE MATERIALIZED VIEW "DailyAggregatedSalesInfo" AS
select "Orders"."id"
from "OrderItems",
     "Orders"
where "OrderItems"."orderId" = "Orders".id
```

**Comment by romansme** [comment] 2023-09-30 09:33
I also think that there is a connection to the fact a change in materialized view query doesn't induce `ALTER` but a `CREATE` statement. 
Maybe this `not exists` condition somehow induces a false indication that the materialized view has changed.

**Comment by romansme** [comment] 2023-10-01 07:46
So basically the big issue here is that the migration is not generated correctly when a change is introduced into a materialized view, in which case I get an error 
cannot modify materialized view <view name> definition

**Comment by a8m** [comment] 2023-10-01 08:24
Thanks for the info. Changing the view definition from `SELECT 'x'` to `SELECT 1` will solve this issue - this happens due to wrong inconsistent normalization done by Atlas/PostgreSQL. A fix will be landed soon. 

Having said this, materialized views were not officially released yet, and considered in beta only. https://atlasgo.io/atlas-schema/hcl#materialized-view

**Closed by a8m** 2023-10-01 08:24 UTC
